# Generated by Django 3.2.8 on 2021-10-08 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30, verbose_name='Client Name')),
                ('purchase_Date', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fact_prod',
            fields=[
                ('id_fp', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.IntegerField(default=0)),
                ('sub_total_price', models.IntegerField(default=0)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_prod', to='factura.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('product_stock', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='fact_prod',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_prod', to='factura.product'),
        ),
    ]
