# Generated by Django 3.2.8 on 2021-10-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20211008_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(related_name='products', through='factura.Fact_prod', to='factura.Product'),
        ),
    ]
