# Generated by Django 3.2.8 on 2021-11-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_bill_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact_prod',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='fact_prod',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Fact_prod',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
